#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libwacom
Version  : 0.5
Release  : 1
URL      : http://ftp.gnome.org/pub/gnome/sources/libwacom/0.5/libwacom-0.5.tar.xz
Source0  : http://ftp.gnome.org/pub/gnome/sources/libwacom/0.5/libwacom-0.5.tar.xz
Summary  : Wacom model feature query library
Group    : Development/Tools
License  : HPND
Requires: libwacom-bin
Requires: libwacom-lib
Requires: libwacom-data
BuildRequires : doxygen
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gudev-1.0)

%description
libwacom is a library to identify wacom tablets and their model-specific
features. It provides easy access to information such as "is this a built-in
on-screen tablet", "what is the size of this model", etc.

%package bin
Summary: bin components for the libwacom package.
Group: Binaries
Requires: libwacom-data

%description bin
bin components for the libwacom package.


%package data
Summary: data components for the libwacom package.
Group: Data

%description data
data components for the libwacom package.


%package dev
Summary: dev components for the libwacom package.
Group: Development
Requires: libwacom-lib
Requires: libwacom-bin
Requires: libwacom-data
Provides: libwacom-devel

%description dev
dev components for the libwacom package.


%package lib
Summary: lib components for the libwacom package.
Group: Libraries
Requires: libwacom-data

%description lib
lib components for the libwacom package.


%prep
%setup -q -n libwacom-0.5

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libwacom-list-local-devices

%files data
%defattr(-,root,root,-)
/usr/share/libwacom/bamboo-one.tablet
/usr/share/libwacom/bamboo-pen-and-touch.tablet
/usr/share/libwacom/cintiq-12wx.tablet
/usr/share/libwacom/cintiq-20wsx.tablet
/usr/share/libwacom/cintiq-21ux.tablet
/usr/share/libwacom/cintiq-21ux2.tablet
/usr/share/libwacom/cintiq-24hd.tablet
/usr/share/libwacom/dtf-720.tablet
/usr/share/libwacom/dti-520.tablet
/usr/share/libwacom/dtu-1631.tablet
/usr/share/libwacom/dtu-2231.tablet
/usr/share/libwacom/generic.tablet
/usr/share/libwacom/graphire-wireless-8x6.tablet
/usr/share/libwacom/graphire3-4x5.tablet
/usr/share/libwacom/graphire3-6x8.tablet
/usr/share/libwacom/graphire4-4x5.tablet
/usr/share/libwacom/intuos-12x12.tablet
/usr/share/libwacom/intuos-12x18.tablet
/usr/share/libwacom/intuos-4x5.tablet
/usr/share/libwacom/intuos-6x8.tablet
/usr/share/libwacom/intuos-9x12.tablet
/usr/share/libwacom/intuos2-12x12.tablet
/usr/share/libwacom/intuos2-12x18.tablet
/usr/share/libwacom/intuos2-4x5.tablet
/usr/share/libwacom/intuos2-6x8.tablet
/usr/share/libwacom/intuos2-9x12.tablet
/usr/share/libwacom/intuos3-12x12.tablet
/usr/share/libwacom/intuos3-12x19.tablet
/usr/share/libwacom/intuos3-4x5.tablet
/usr/share/libwacom/intuos3-4x6.tablet
/usr/share/libwacom/intuos3-6x11.tablet
/usr/share/libwacom/intuos3-6x8.tablet
/usr/share/libwacom/intuos3-9x12.tablet
/usr/share/libwacom/intuos4-12x19.tablet
/usr/share/libwacom/intuos4-4x6.tablet
/usr/share/libwacom/intuos4-6x9-wl.tablet
/usr/share/libwacom/intuos4-6x9.tablet
/usr/share/libwacom/intuos4-8x13.tablet
/usr/share/libwacom/intuos5-m.tablet
/usr/share/libwacom/intuos5-s.tablet
/usr/share/libwacom/intuos5-touch-l.tablet
/usr/share/libwacom/intuos5-touch-m.tablet
/usr/share/libwacom/intuos5-touch-s.tablet
/usr/share/libwacom/isdv4-e3.tablet
/usr/share/libwacom/isdv4-e6.tablet
/usr/share/libwacom/libwacom.stylus
/usr/share/libwacom/serial-wacf004.tablet

%files dev
%defattr(-,root,root,-)
/usr/include/libwacom-1.0/libwacom/libwacom.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
